import 'server-only';

import ExcelJS from 'exceljs';

import { normalizeArabic, normalizeDigits } from '@/lib/arabic';
import { JORDAN_MOBILE_PATTERN, NATIONAL_ID_PATTERN } from '../schemas/organization';
import type { ImportIssue } from './types';

/**
 * Reading an organizations worksheet.
 *
 * Shared by the preview step and the commit step so that what the user is shown
 * before importing is produced by exactly the code that will do the importing —
 * a preview generated by a second, similar parser is a preview of nothing.
 *
 * The traps here are specific to this dataset, which came out of MS Access:
 *
 *  - Mobile numbers carry a leading zero. Read as a number, `0785876407`
 *    becomes 785876407 and the number is wrong for every row.
 *  - National IDs sometimes arrive as floats (`419935010.0`).
 *  - Establishment dates arrive as real Date objects in the local timezone;
 *    formatting them anywhere but UTC can move them a day.
 *  - The export includes Access form artifacts (`Combo_StateSearch`, `Text44`)
 *    that are not data.
 */

/** The fields an import can populate. */
export type OrganizationImportField =
  | 'name'
  | 'district'
  | 'classification'
  | 'nationalId'
  | 'establishedAt'
  | 'directorName'
  | 'mobile'
  | 'serialNo';

/** The fields a member import can populate. */
export type MemberImportField = 'name' | 'nationalId' | 'mobile' | 'jobTitle';

/**
 * Recognised header spellings, normalized for lookup.
 *
 * Includes both the raw Access column names (so the merged file imports with no
 * manual editing) and the Arabic headers this app's own template emits.
 */
const HEADER_ALIASES: Record<string, OrganizationImportField> = {};

function registerAliases(field: OrganizationImportField, aliases: string[]): void {
  for (const alias of aliases) {
    HEADER_ALIASES[normalizeHeader(alias)] = field;
  }
}

/** Header lookup key: case-, space- and separator-insensitive. */
function normalizeHeader(header: string): string {
  return normalizeArabic(header).replace(/[\s_\-.]+/g, '');
}

registerAliases('name', ['Org_Name', 'اسم الجمعية', 'الاسم', 'name']);
registerAliases('district', ['Org_stat', 'اللواء', 'المنطقة', 'district']);
registerAliases('classification', ['Org_class', 'التصنيف', 'classification']);
registerAliases('nationalId', ['Org_ID_National', 'الرقم الوطني', 'nationalId', 'national id']);
registerAliases('establishedAt', [
  'Org_EstablishmentDate',
  'تاريخ التأسيس',
  'establishedAt',
  'establishment date'
]);
registerAliases('directorName', ['Name_Director', 'اسم المدير', 'المدير', 'directorName']);
registerAliases('mobile', ['Mobile', 'رقم الهاتف', 'الهاتف', 'الجوال', 'mobile']);
registerAliases('serialNo', ['txtNum', 'التسلسل', 'الرقم', 'serialNo']);

/** Fields without which a row cannot be stored. */
export const REQUIRED_FIELDS: OrganizationImportField[] = ['name', 'district'];

/** Header text from the source that is a form artifact rather than data. */
const IGNORED_HEADERS = new Set(
  ['Combo_StateSearch', 'Combo_ClassSearch', 'Text44', 'Text16'].map(normalizeHeader)
);

export type ParsedRow = {
  /** 1-based worksheet row number, so an issue points at what Excel shows. */
  rowNumber: number;
  name: string;
  district: string;
  classification: string | null;
  nationalId: string | null;
  establishedAt: string | null;
  directorName: string | null;
  mobile: string | null;
  serialNo: number | null;
};

export type ParsedWorkbook = {
  detectedHeaders: string[];
  mapping: Record<string, OrganizationImportField>;
  unmappedHeaders: string[];
  missingRequired: OrganizationImportField[];
  rows: ParsedRow[];
  /** Values that were stored despite being questionable. */
  warnings: ImportIssue[];
  /** Rows that could not be read at all. */
  errors: ImportIssue[];
};

/** Renders a cell as trimmed text, whatever type ExcelJS handed back. */
function cellText(cell: ExcelJS.Cell): string {
  const value = cell.value;

  if (value === null || value === undefined) return '';

  if (typeof value === 'object') {
    // Rich text, hyperlinks and formula results are objects; `cell.text` is
    // ExcelJS's own rendering of them and is right in every case here.
    if (value instanceof Date) return cell.text.trim();
    if ('richText' in value) {
      return value.richText
        .map((part) => part.text)
        .join('')
        .trim();
    }
    if ('text' in value && typeof value.text === 'string') return value.text.trim();
    if ('result' in value) return String(value.result ?? '').trim();
    return cell.text.trim();
  }

  return String(value).trim();
}

/** Formats a Date as `YYYY-MM-DD` using its UTC parts. */
function toIsoDate(date: Date): string {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Coerces a cell to a `YYYY-MM-DD` string.
 *
 * ExcelJS returns a Date for date-formatted cells. Serial numbers appear when a
 * column was never formatted as a date — those are days since the 1900 epoch,
 * with Excel's deliberate non-existent 1900-02-29 accounted for by the -25569
 * offset.
 */
function toDateString(cell: ExcelJS.Cell): { value: string | null; invalid: boolean } {
  const raw = cell.value;

  if (raw === null || raw === undefined || raw === '') return { value: null, invalid: false };

  if (raw instanceof Date) return { value: toIsoDate(raw), invalid: false };

  if (typeof raw === 'number') {
    const asDate = new Date((raw - 25569) * 86400 * 1000);
    return Number.isNaN(asDate.getTime())
      ? { value: null, invalid: true }
      : { value: toIsoDate(asDate), invalid: false };
  }

  const text = cellText(cell);
  if (!text) return { value: null, invalid: false };

  const parsed = new Date(text);
  return Number.isNaN(parsed.getTime())
    ? { value: null, invalid: true }
    : { value: toIsoDate(parsed), invalid: false };
}

/**
 * Reads a mobile number without losing its leading zero.
 *
 * If Excel stored the column as numeric the zero is already gone from the
 * stored value, so a nine-digit result starting with `7` is restored to ten
 * digits. That is a repair of a known spreadsheet defect, not a guess: every
 * Jordanian mobile in this registry is `07` followed by eight digits.
 */
function toMobile(cell: ExcelJS.Cell): string | null {
  const digits = normalizeDigits(cellText(cell));
  if (!digits) return null;
  if (digits.length === 9 && digits.startsWith('7')) return `0${digits}`;
  return digits;
}

function toNationalId(cell: ExcelJS.Cell): string | null {
  const digits = normalizeDigits(cellText(cell));
  return digits || null;
}

function toSerialNo(cell: ExcelJS.Cell): number | null {
  const digits = normalizeDigits(cellText(cell));
  if (!digits) return null;
  const parsed = Number(digits);
  return Number.isSafeInteger(parsed) ? parsed : null;
}

function emptyToNull(value: string): string | null {
  return value === '' ? null : value;
}

/**
 * Parses the first worksheet of an xlsx buffer.
 *
 * Never throws on bad row content — a row that cannot be read becomes an entry
 * in `errors` and the rest of the file still imports. Only a structurally
 * unreadable file throws.
 */
export async function parseOrganizationsWorkbook(buffer: ArrayBuffer): Promise<ParsedWorkbook> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const worksheet = workbook.worksheets[0];
  if (!worksheet) {
    throw new Error('الملف لا يحتوي على أي ورقة عمل.');
  }

  const headerRow = worksheet.getRow(1);
  const detectedHeaders: string[] = [];
  const mapping: Record<string, OrganizationImportField> = {};
  const unmappedHeaders: string[] = [];
  /** Worksheet column number -> field. */
  const columnByField = new Map<OrganizationImportField, number>();

  headerRow.eachCell({ includeEmpty: false }, (cell, columnNumber) => {
    const header = cellText(cell);
    if (!header) return;

    detectedHeaders.push(header);

    const key = normalizeHeader(header);
    const field = HEADER_ALIASES[key];

    if (!field) {
      if (!IGNORED_HEADERS.has(key)) unmappedHeaders.push(header);
      return;
    }

    // First occurrence wins, so a duplicated header cannot silently shadow the
    // column that was already mapped.
    if (!columnByField.has(field)) {
      columnByField.set(field, columnNumber);
      mapping[header] = field;
    }
  });

  const missingRequired = REQUIRED_FIELDS.filter((field) => !columnByField.has(field));

  const rows: ParsedRow[] = [];
  const warnings: ImportIssue[] = [];
  const errors: ImportIssue[] = [];

  if (missingRequired.length > 0) {
    return {
      detectedHeaders,
      mapping,
      unmappedHeaders,
      missingRequired,
      rows,
      warnings,
      errors
    };
  }

  const cellFor = (row: ExcelJS.Row, field: OrganizationImportField) => {
    const column = columnByField.get(field);
    return column ? row.getCell(column) : undefined;
  };
  const textFor = (row: ExcelJS.Row, field: OrganizationImportField) => {
    const cell = cellFor(row, field);
    return cell ? cellText(cell) : '';
  };

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return;

    const name = textFor(row, 'name');
    const district = textFor(row, 'district');

    // A trailing blank row is normal in exported sheets — skip silently rather
    // than reporting it as an error the user cannot act on.
    if (!name && !district && !textFor(row, 'nationalId')) return;

    if (!name) {
      errors.push({ row: rowNumber, column: 'Org_Name', message: 'اسم الجمعية مفقود' });
      return;
    }
    if (!district) {
      errors.push({ row: rowNumber, column: 'Org_stat', message: 'اللواء مفقود' });
      return;
    }

    const dateCell = cellFor(row, 'establishedAt');
    const date = dateCell ? toDateString(dateCell) : { value: null, invalid: false };
    if (date.invalid) {
      warnings.push({
        row: rowNumber,
        column: 'Org_EstablishmentDate',
        message: `تاريخ غير صالح — تم تجاهله: «${textFor(row, 'establishedAt')}»`
      });
    }

    const mobileCell = cellFor(row, 'mobile');
    const mobile = mobileCell ? toMobile(mobileCell) : null;
    if (mobile && !JORDAN_MOBILE_PATTERN.test(mobile)) {
      warnings.push({
        row: rowNumber,
        column: 'Mobile',
        message: `رقم هاتف غير مطابق للصيغة (07XXXXXXXX): «${mobile}» — تم حفظه كما هو`
      });
    }

    const nationalIdCell = cellFor(row, 'nationalId');
    const nationalId = nationalIdCell ? toNationalId(nationalIdCell) : null;
    if (nationalId && !NATIONAL_ID_PATTERN.test(nationalId)) {
      warnings.push({
        row: rowNumber,
        column: 'Org_ID_National',
        message: `الرقم الوطني غير مكوّن من ٩ أو ١٠ أرقام: «${nationalId}» — تم حفظه كما هو`
      });
    }

    const serialCell = cellFor(row, 'serialNo');

    rows.push({
      rowNumber,
      name,
      district,
      classification: emptyToNull(textFor(row, 'classification')),
      nationalId,
      establishedAt: date.value,
      directorName: emptyToNull(textFor(row, 'directorName')),
      mobile,
      serialNo: serialCell ? toSerialNo(serialCell) : null
    });
  });

  return { detectedHeaders, mapping, unmappedHeaders, missingRequired, rows, warnings, errors };
}

// ============================================================
// Members Workbook
// ============================================================

const MEMBER_HEADER_ALIASES: Record<string, MemberImportField> = {};

function registerMemberAliases(field: MemberImportField, aliases: string[]): void {
  for (const alias of aliases) {
    MEMBER_HEADER_ALIASES[normalizeHeader(alias)] = field;
  }
}

registerMemberAliases('name', ['الاسم', 'اسم العضو', 'name']);
registerMemberAliases('nationalId', ['الرقم الوطني', 'nationalId']);
registerMemberAliases('mobile', ['رقم الهاتف', 'الهاتف', 'الجوال', 'mobile']);
registerMemberAliases('jobTitle', ['المسمى الوظيفي', 'الوظيفة', 'jobTitle', 'job title']);

export const MEMBER_REQUIRED_FIELDS: MemberImportField[] = ['name'];

export type ParsedMemberRow = {
  rowNumber: number;
  name: string;
  nationalId: string;
  mobile: string;
  jobTitle: string;
};

export type ParsedMembersWorkbook = {
  detectedHeaders: string[];
  mapping: Record<string, MemberImportField>;
  unmappedHeaders: string[];
  missingRequired: MemberImportField[];
  rows: ParsedMemberRow[];
  errors: ImportIssue[];
  warnings: ImportIssue[];
};

export async function parseMembersWorkbook(buffer: ArrayBuffer): Promise<ParsedMembersWorkbook> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const worksheet = workbook.worksheets[0];
  if (!worksheet) {
    throw new Error('الملف لا يحتوي على أي ورقة عمل.');
  }

  const headerRow = worksheet.getRow(1);
  const detectedHeaders: string[] = [];
  const mapping: Record<string, MemberImportField> = {};
  const unmappedHeaders: string[] = [];
  const columnByField = new Map<MemberImportField, number>();

  headerRow.eachCell({ includeEmpty: false }, (cell, columnNumber) => {
    const header = cellText(cell);
    if (!header) return;

    detectedHeaders.push(header);

    const key = normalizeHeader(header);
    const field = MEMBER_HEADER_ALIASES[key];

    if (!field) {
      unmappedHeaders.push(header);
      return;
    }

    if (!columnByField.has(field)) {
      columnByField.set(field, columnNumber);
      mapping[header] = field;
    }
  });

  const missingRequired = MEMBER_REQUIRED_FIELDS.filter((field) => !columnByField.has(field));

  const rows: ParsedMemberRow[] = [];
  const warnings: ImportIssue[] = [];
  const errors: ImportIssue[] = [];

  if (missingRequired.length > 0) {
    return { detectedHeaders, mapping, unmappedHeaders, missingRequired, rows, errors, warnings };
  }

  const cellFor = (row: ExcelJS.Row, field: MemberImportField) => {
    const column = columnByField.get(field);
    return column ? row.getCell(column) : undefined;
  };
  const textFor = (row: ExcelJS.Row, field: MemberImportField) => {
    const cell = cellFor(row, field);
    return cell ? cellText(cell) : '';
  };

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return;

    const name = textFor(row, 'name');
    if (!name) return;

    const nationalIdCell = cellFor(row, 'nationalId');
    const nationalId = nationalIdCell ? normalizeDigits(cellText(nationalIdCell)) : '';

    const mobileCell = cellFor(row, 'mobile');
    const mobile = mobileCell ? (toMobile(mobileCell) ?? '') : '';

    if (mobile && !JORDAN_MOBILE_PATTERN.test(mobile)) {
      warnings.push({
        row: rowNumber,
        column: 'mobile',
        message: `رقم هاتف غير مطابق للصيغة (07XXXXXXXX): «${mobile}» — تم حفظه كما هو`
      });
    }

    rows.push({
      rowNumber,
      name,
      nationalId,
      mobile,
      jobTitle: textFor(row, 'jobTitle')
    });
  });

  return { detectedHeaders, mapping, unmappedHeaders, missingRequired, rows, errors, warnings };
}
